cmake_minimum_required(VERSION 3.24)

foreach(argument IN ITEMS FLS_ASSET_SOURCE FLS_ASSET_DESTINATION FLS_ASSET_MANIFEST)
    if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing asset deployment argument: ${argument}")
    endif()
endforeach()

cmake_path(ABSOLUTE_PATH FLS_ASSET_SOURCE NORMALIZE OUTPUT_VARIABLE source)
cmake_path(ABSOLUTE_PATH FLS_ASSET_DESTINATION NORMALIZE OUTPUT_VARIABLE destination)
cmake_path(GET destination FILENAME destination_name)
cmake_path(IS_PREFIX source "${destination}" NORMALIZE source_overlap)
cmake_path(IS_PREFIX destination "${source}" NORMALIZE destination_overlap)
if(NOT destination_name STREQUAL "assets" OR source_overlap OR destination_overlap
        OR IS_SYMLINK "${destination}" OR (EXISTS "${destination}" AND NOT IS_DIRECTORY "${destination}"))
    message(FATAL_ERROR "Unsafe asset deployment destination: ${destination}")
endif()

include("${FLS_ASSET_MANIFEST}")
if(NOT FLS_GUI_ASSET_FILES)
    message(FATAL_ERROR "The GUI asset manifest is empty")
endif()
foreach(relative IN LISTS FLS_GUI_ASSET_FILES)
    cmake_path(IS_ABSOLUTE relative absolute)
    if(absolute OR relative MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)")
        message(FATAL_ERROR "Invalid relative asset path: ${relative}")
    endif()
    if(NOT EXISTS "${source}/${relative}" OR IS_DIRECTORY "${source}/${relative}")
        message(FATAL_ERROR "Required GUI asset is missing: ${source}/${relative}. Existing runtime assets were not changed.")
    endif()
endforeach()

file(LOCK "${destination}.deploy.lock" GUARD PROCESS TIMEOUT 0 RESULT_VARIABLE lock_error)
if(NOT lock_error STREQUAL "0")
    message(FATAL_ERROR "Cannot acquire asset deployment lock: ${lock_error}")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(stage "${destination}.stage-${suffix}")
set(backup "${destination}.previous-${suffix}")
if(EXISTS "${stage}" OR EXISTS "${backup}")
    message(FATAL_ERROR "Asset staging path already exists")
endif()
file(MAKE_DIRECTORY "${stage}")
foreach(relative IN LISTS FLS_GUI_ASSET_FILES)
    get_filename_component(directory "${stage}/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(COPY_FILE "${source}/${relative}" "${stage}/${relative}" RESULT copy_error)
    if(NOT copy_error STREQUAL "0")
        file(REMOVE_RECURSE "${stage}")
        message(FATAL_ERROR "Cannot stage GUI asset ${relative}: ${copy_error}. Existing runtime assets were not changed.")
    endif()
endforeach()

if(EXISTS "${destination}")
    file(RENAME "${destination}" "${backup}" RESULT backup_error NO_REPLACE)
    if(NOT backup_error STREQUAL "0")
        file(REMOVE_RECURSE "${stage}")
        message(FATAL_ERROR "Cannot preserve existing runtime assets: ${backup_error}")
    endif()
endif()
file(RENAME "${stage}" "${destination}" RESULT publish_error NO_REPLACE)
if(NOT publish_error STREQUAL "0")
    if(EXISTS "${backup}")
        file(RENAME "${backup}" "${destination}" RESULT restore_error NO_REPLACE)
        if(NOT restore_error STREQUAL "0")
            message(FATAL_ERROR "Cannot publish runtime assets: ${publish_error}. Previous assets remain at ${backup}; staged assets remain at ${stage}.")
        endif()
    endif()
    file(REMOVE_RECURSE "${stage}")
    message(FATAL_ERROR "Cannot publish runtime assets: ${publish_error}")
endif()
if(EXISTS "${backup}")
    file(REMOVE_RECURSE "${backup}")
endif()
list(LENGTH FLS_GUI_ASSET_FILES asset_count)
message(STATUS "Deployed ${asset_count} validated GUI assets to ${destination}")
