#!/usr/bin/env python3
"""Generate the compact C++ House 8 garage-layout contract from decoded game data."""

import argparse
import struct
import xml.etree.ElementTree as ET
from pathlib import Path, PureWindowsPath


FNV64_OFFSET = 0xCBF29CE484222325
FNV64_PRIME = 0x100000001B3
UINT64_MASK = (1 << 64) - 1


class BinaryReader:
    def __init__(self, data: bytes):
        self.data = data
        self.offset = 0

    def read(self, fmt: str):
        size = struct.calcsize(fmt)
        values = struct.unpack_from(fmt, self.data, self.offset)
        self.offset += size
        return values[0] if len(values) == 1 else values

    def read_bytes(self, size: int) -> bytes:
        value = self.data[self.offset:self.offset + size]
        self.offset += size
        return value


def read_bxml(path: Path) -> ET.Element:
    reader = BinaryReader(path.read_bytes())
    if reader.read_bytes(4) != b"BXML":
        raise ValueError(f"{path}: missing BXML header")
    version = reader.read("<B")
    if version > 2:
        raise ValueError(f"{path}: unsupported BXML version {version}")
    string_count = reader.read("<i")
    reader.read("<I")  # String-table byte size.
    strings = []
    for _ in range(string_count):
        size = reader.read("<h")
        strings.append(reader.read_bytes(size).decode("utf-8"))
    if reader.read("<B") == 0:
        raise ValueError(f"{path}: no root node")

    def read_string() -> str:
        if string_count > 0xFFFF:
            index = reader.read("<i")
        elif string_count > 0xFF:
            index = reader.read("<H")
        else:
            index = reader.read("<B")
        return strings[index]

    def read_node() -> ET.Element:
        flags = reader.read("<B")
        element = ET.Element(read_string())
        if flags & 2:
            for _ in range(reader.read("<B")):
                element.set(read_string(), read_string())
        if flags & 4:
            for _ in range(reader.read("<H")):
                element.append(read_node())
        return element

    return read_node()


def fnv1a64(text: str) -> int:
    result = FNV64_OFFSET
    for byte in text.encode("utf-8"):
        result = ((result ^ byte) * FNV64_PRIME) & UINT64_MASK
    return result


def prop_catalog(root: ET.Element) -> dict[int, str]:
    result = {}
    data = root.find('./object/property[@id="Data"]')
    if data is None:
        raise ValueError("PropsSet has no Data property")
    for item in data.findall("./map_element"):
        key = item.find("./key")
        value = item.find("./value")
        if key is None or value is None:
            continue
        identifier = key.get("value", "")
        model = value.find('./property[@id="ModelPath"]')
        if not identifier or model is None or not model.get("value"):
            continue
        model_path = PureWindowsPath(model.get("value"))
        archive = model_path.parent / f"{model_path.stem}.i.zip"
        result[fnv1a64(identifier)] = archive.as_posix()
    return result


def cpp_float(value: str) -> str:
    number = float(value)
    if number == 0.0:
        number = 0.0
    literal = f"{number:.9g}"
    if "." not in literal and "e" not in literal:
        literal += ".0"
    return literal + "f"


def generate(layout_path: Path, props_path: Path) -> str:
    layout = ET.parse(layout_path).getroot()
    catalog = prop_catalog(read_bxml(props_path))
    entries = layout.findall("./Props/Prop")
    unique_ids = sorted({int(entry.get("guid", "0")) for entry in entries})
    missing = [identifier for identifier in unique_ids if identifier not in catalog]
    if missing:
        raise ValueError(f"unresolved House 8 prop IDs: {missing}")

    lines = [
        "// Generated by tools/generate_tokyo_house_layout.py from Default-House8.xml",
        "// and ObjectModelGame PropsSet data. Do not edit by hand.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace fh6::tokyo_house_layout {",
        "",
        "struct PropAsset {",
        "    std::uint64_t id;",
        "    const char *archive;",
        "};",
        "",
        "struct PropInstance {",
        "    std::uint64_t id;",
        "    std::array<float, 16> transform;",
        "};",
        "",
        f"inline constexpr std::array<PropAsset, {len(unique_ids)}> kAssets = {{{{",
    ]
    for identifier in unique_ids:
        escaped = catalog[identifier].replace('\\', '/').replace('"', '\\"')
        lines.append(f'    {{{identifier}ull, "{escaped}"}},')
    lines.extend(["}};", "", f"inline constexpr std::array<PropInstance, {len(entries)}> kInstances = {{{{"])
    for entry in entries:
        values = [cpp_float(entry.get(f"transform._{row}{column}", "0"))
                  for row in range(1, 5) for column in range(1, 5)]
        lines.append(f"    {{{entry.get('guid')}ull, {{{', '.join(values)}}}}},")
    lines.extend(["}};", "", "} // namespace fh6::tokyo_house_layout", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("layout", type=Path)
    parser.add_argument("props_set", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    output = generate(args.layout, args.props_set)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
